name: CI/CD

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Build
        run: |
          mkdir -p build
          for dir in $(find ./cmd -type d -maxdepth 1 -mindepth 1);
          do
            go build -o build ${dir}
          done
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

  docker:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
