name: CI/CD

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64]
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Build
        run: |
          mkdir -p build
          for dir in $(find ./cmd -type d -maxdepth 1 -mindepth 1);
          do
            go build -o build ${dir}
          done
          zip -j $(echo $GITHUB_REPOSITORY | cut -d '/' -f2)_${GOOS}_${GOARCH}.zip build/*
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}.zip
          path: '*.zip'

  release:
    name: Release
    if: github.event_name == 'push' && github.ref != 'refs/heads/develop'
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Create release and publish
        id: release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.1.1
          extra_plugins: |
            conventional-changelog-conventionalcommits@^4.4.0
            @semantic-release/git@^9.0.0
            @semantic-release/exec@^5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

