name: CI/CD

on:
  push:
    branches:
      - master
      - develop
      - beta
      - alpha
      - "[0-9]+.x"
      - "[0-9]+.[0-9]+.x"
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - run: |
          make
